### ISSUE TITLE
Will you make this project find and report where errors are?

### ISSUE THREAD

**Issue by surfer190** [ramonsaraiva/jinjaninja#3]
Will you make this project find and report where errors are?

**Comment by ramonsaraiva** [comment]
Not sure what type of errors you're talking about, but for now, it only verifies a few code styles issues as mentioned in README

**Comment by dkdndes** [comment]
I suggest to close this, due to the existing information (line, position) in the error message:

      templates/base.html:3:44 Block closures should also have names `{% endblock %}`
